language: java
jdk:
  - openjdk8

#branches
# Travis CI를 어느 브랜치가 푸시될 때 수행할 지 지정 (아래는 오직 master 브랜치에 push될 때만 수행)
branches:
  only:
    - master

#cache
# 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐싱하여, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

#script
# master 브랜치에 푸시되었을 때 수행하는 명령어.
script: "./gradlew clean build"

before_deploy:
  - zip -r pt-springboot *
  - mkdir -p deploy
  - mv pt-springboot.zip deploy/pt-springboot.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key : $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: pt-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip file 접근을 private로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - choipyunghwa@naver.com